import os
from io import BytesIO
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

def create_wud_word(touchpoint_data: dict) -> BytesIO:
    """Generates a native Word doc matching the official SBIL corporate WUD standard."""
    
    # 1. TEMPORARY STATIC RESPONSE FOR UI TESTING
    ai_summary = "MOCK AI SUMMARY: This integration facilitates seamless data transfer between the source and target systems."
    
    # 2. Extract Variables safely
    td = touchpoint_data.get('techDetails', {})
    wud_id = touchpoint_data.get('id', 'TBD')
    api_name = touchpoint_data.get('name', td.get('apiName', 'Unnamed Integration'))
    target_sys = touchpoint_data.get('target', 'Target System')
    source_sys = touchpoint_data.get('source', 'Source System')
    owner = touchpoint_data.get('owner', 'SDGNext Team')
    business_purpose = touchpoint_data.get('business_purpose', 'No functional requirements listed.')
    
    # Initialize Document
    doc = Document()

    # ==========================================
    # PAGE 1: TITLE PAGE
    # ==========================================
    doc.add_paragraph("\n\n\n\n\n\n")
    
    title = doc.add_paragraph(f"{api_name}\nWork Unit Document (WUD ID: {wud_id})")
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.runs[0]
    title_run.font.size = Pt(28)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(0, 51, 102) # Corporate Blue

    doc.add_page_break()

    # ==========================================
    # PAGE 2: PROPRIETARY & VERSION CONTROL
    # ==========================================
    conf_heading = doc.add_heading('Confidential and Proprietary Information', level=2)
    conf_heading.runs[0].font.color.rgb = RGBColor(0, 0, 0)
    
    doc.add_paragraph(
        "This document is confidential and contains ideas, concepts, processes, and other information considered proprietary. "
        "Readers are to treat the information contained herein as confidential and may not disseminate; copy or reproduce it in any form."
    )
    
    doc.add_heading('Version Control', level=2)
    
    # Version Control Table
    vc_table = doc.add_table(rows=2, cols=5)
    vc_table.style = 'Table Grid'
    vc_headers = ["Sr. No.", "Date", "Version", "Description", "Author"]
    for i, header in enumerate(vc_headers):
        cell = vc_table.rows[0].cells[i]
        cell.text = header
        cell.paragraphs[0].runs[0].font.bold = True
        
    vc_table.rows[1].cells[0].text = "1"
    vc_table.rows[1].cells[1].text = datetime.now().strftime("%d-%m-%Y")
    vc_table.rows[1].cells[2].text = "1.0"
    vc_table.rows[1].cells[3].text = "Initial WUD Generation via SDGNext"
    vc_table.rows[1].cells[4].text = owner

    doc.add_page_break()

    # ==========================================
    # PAGE 3: MAIN CONTENT
    # ==========================================
    
    # 1. Introduction
    doc.add_heading('1. Introduction', level=1)
    doc.add_paragraph(f"The '{api_name}' integration is used to facilitate the following business objective: {business_purpose}")
    doc.add_paragraph(f"Architecture Summary: {ai_summary}")

    # 2. Integration Overview
    doc.add_heading(f'2. {api_name}', level=1)
    doc.add_paragraph(f"Source System: - {source_sys}", style='List Bullet')
    doc.add_paragraph(f"Target System: - {target_sys}", style='List Bullet')

    # 2.1 Technical Details
    doc.add_heading('2.1. Technical Details', level=2)
    doc.add_paragraph("Following are the technical details:")
    
    # The massive Technical Details Table from your uploaded doc
    tech_table = doc.add_table(rows=16, cols=2)
    tech_table.style = 'Table Grid'
    tech_table.autofit = False
    tech_table.columns[0].width = Inches(2.0)
    tech_table.columns[1].width = Inches(4.5)

    # Mapping your DB variables to the exact rows from your corporate document
    table_data = [
        ("WUD ID", str(wud_id)),
        ("Source System", source_sys),
        ("Target System", target_sys),
        ("Owner", owner),
        ("Authentication", td.get('apiAuth', 'N/A')),
        ("Periodicity", "On Demand"),
        ("Interface", "API"),
        ("Methodology", td.get('apiMethod', 'NA')),
        ("API Type", td.get('apiType', 'RESTFUL')),
        ("EDS Name", api_name),
        ("Input Request Payload", td.get('apiReq', 'NA')),
        ("Output Response Payload", td.get('apiRes', 'NA')),
        ("Failure Response", "If Invalid Response is passed it will display respective error messages in response."),
        # --- NEW & UPDATED ROWS ---
        ("Expected Output", touchpoint_data.get('expected_output', 'To be generated by AI')), 
        ("Macro Logic", touchpoint_data.get('business_flow', 'To be generated by AI')),
        ("Testing Strategy", "EDS will be tested as a part of functional scenario testing. Explicit testing can be performed through the Widget."),
        ("Watchouts", "For unhandled exceptions, application user needs to contact application administrator. Service must be accessible from target environments.")
    ]

    # The massive Technical Details Table (Now automatically sizes to len(table_data)!)
    tech_table = doc.add_table(rows=len(table_data), cols=2)
    tech_table.style = 'Table Grid'
    tech_table.autofit = False
    tech_table.columns[0].width = Inches(2.0)
    tech_table.columns[1].width = Inches(4.5)

    for i, (key, val) in enumerate(table_data):
        cell_left = tech_table.rows[i].cells[0]
        cell_right = tech_table.rows[i].cells[1]
        
        cell_left.text = key
        cell_left.paragraphs[0].runs[0].font.bold = True
        
        cell_right.text = str(val) if val else "NA"

    doc.add_paragraph("\n")
    
    # Conclusion
    doc.add_heading('CONCLUSION', level=1)
    doc.add_paragraph(f"This WUD document formalizes the technical execution plan for the {api_name} integration.")

    # ==========================================
    # FINALIZATION
    # ==========================================
    word_buffer = BytesIO()
    doc.save(word_buffer)
    word_buffer.seek(0)
    
    return word_buffer