import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from io import BytesIO

# --- UPDATE THESE LINES ---
SMTP_SERVER = "smtp.gmail.com"  
SMTP_PORT = 587
SMTP_USERNAME = "mahi.sirvi@gmail.com"
SMTP_PASSWORD = "klrynpcgevlubkfj"

def send_rgt_invite(target_email: str, touchpoint_data: dict, rgt_buffer: BytesIO) -> bool:
    """
    Sends the Requirement Gathering Template to the bank.
    Returns True if successful, False if it fails.
    """
    wud_id = touchpoint_data.get('id', 'TBD')
    api_name = touchpoint_data.get('name', 'Unnamed Integration')

    # 1. Construct the Email Container
    msg = MIMEMultipart()
    msg['From'] = SMTP_USERNAME
    msg['To'] = target_email
    
    # CRITICAL: The Subject MUST contain the tracking ID for the inbound parser
    msg['Subject'] = f"ACTION REQUIRED: Technical Specifications for {api_name} [WUD-ID:{wud_id}]"

    # 2. Construct the Email Body
    body = f"""
    Hello Team,
    
    We are initiating the integration process for the '{api_name}' touchpoint.
    
    Attached is the Requirement Gathering Template (RGT). We have pre-filled the known functional 
    requirements. 
    
    Action Required:
    1. Open the attached Word document.
    2. Fill in the required technical details in the white cells (Base URL, Payloads, Auth).
    3. Save the document.
    4. Reply directly to this email with the updated document attached.
    
    Please do not alter the structure of the table or change the email subject line, as your 
    response will be processed automatically by our systems.
    
    Regards,
    SDGNext Command Center
    """
    msg.attach(MIMEText(body, 'plain'))

    # 3. Attach the Word Document
    # We read the BytesIO buffer generated by your rgt_engine
    word_attachment = MIMEApplication(
        rgt_buffer.read(), 
        _subtype="vnd.openxmlformats-officedocument.wordprocessingml.document"
    )
    word_attachment.add_header(
        'Content-Disposition', 
        'attachment', 
        filename=f"RGT_{api_name}_Spec.docx"
    )
    msg.attach(word_attachment)

    # 4. Send the Email
    try:
        if SMTP_PORT == 465:
            # SSL Connection
            with smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT) as server:
                server.login(SMTP_USERNAME, SMTP_PASSWORD)
                server.send_message(msg)
        else:
            # TLS Connection (Port 587)
            with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
                server.starttls()
                server.login(SMTP_USERNAME, SMTP_PASSWORD)
                server.send_message(msg)
                
        print(f"RGT successfully dispatched to {target_email} for WUD-ID {wud_id}")
        return True
        
    except Exception as e:
        print(f"Failed to send RGT email: {e}")
        return False